### ISSUE TITLE
semver.satisfies throws TypeError when no match instead of returning false

### ISSUE THREAD

**Issue by getsnoopy** [npm/node-semver#189]
When using `semver.satisfies`, the contract is to return a boolean of whether the `version` satisfies the `range` or not. But when it doesn't satisfy it, it's throwing a TypeError rather than returning `false`:

```
TypeError: Invalid Version: 6.7.2 invalid
    at new SemVer (/Users/getsnoopy/test/node_modules/semver/semver.js:293:11)
    at Range.test (/Users/getsnoopy/test/node_modules/semver/semver.js:1036:15)
    at Function.satisfies (/Users/getsnoopy/test/node_modules/semver/semver.js:1085:16)
```

**Comment by isaacs** [comment]
It looks like you're passing in a thing that isn't a valid semver?

```
$ node -p 'require("./").satisfies("6.7.2", "1.x")'
false

$ node -p 'require("./").satisfies("6.7.2 invalid", "1.x")'
/Users/isaacs/dev/js/semver/semver.js:293
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: 6.7.2 invalid
```
