### ISSUE TITLE
Why is `^4.17.4` not a valid version number

### ISSUE THREAD

**Issue by denisflorkin** [npm/node-semver#191]
Hello, I'm trying to do basic comparaison of version, without success...
I read the version number directly from the package.json
this is what I eventually end up running I run : 

`semver.gt( '^4.17.4', '^9.17.0' ) // => TypeError: Invalid Version: ^4.17.4`

I tried adding clean() and valid(), but they just return null, which is expected for an unvalid version number.

My question is how is this an invalid version number: `^4.17.4` ? 
https://semver.npmjs.com/ does not seems to complain when I enter it into the field
When I run npm, it does not seems to complain either...

the error:
```
TypeError: Invalid Version: ^4.17.4
    at new SemVer (/Users/denisflorkin/Projects/cluedin-app/node_modules/semver/semver.js:293:11)
    at compare (/Users/denisflorkin/Projects/cluedin-app/node_modules/semver/semver.js:566:10)
    at Function.gt (/Users/denisflorkin/Projects/cluedin-app/node_modules/semver/semver.js:595:10)
    at extractLatestDeps (/Users/denisflorkin/Projects/cluedin-app/script/index.js:33:23)
    at Array.reduce (native)
    at program (/Users/denisflorkin/Projects/cluedin-app/script/index.js:278:8)
    at program.next (<anonymous>)
    at iterate (/Users/denisflorkin/Projects/cluedin-app/script/utils.js:19:14)
    at runGenerator (/Users/denisflorkin/Projects/cluedin-app/script/utils.js:41:5)
    at Object.<anonymous> (/Users/denisflorkin/Projects/cluedin-app/script/index.js:310:1)
```

**Comment by isaacs** [comment]
I'm guessing you figured this out, since you closed the issue, but for posterity: `^4.17.4` is a SemVer Range, equivalent to `>=4.17.4 <5.0.0`.  Ranges are greater or less than other ranges, because they can overlap, or be ambiguous.  As human beings we can of course say that any version that satisfies `^4.17.4` will be less than any version that satisfies `^9.17.0`, but it's tricky to do that in a general way, since you could have a range like `1.x || 3.x || 5.x` and another range that's `0.x || 2.x || 4.x` and even though they don't intersect, it's not clear which is "greater than" the other.
