### ISSUE TITLE
Breaking change in 5.4.0: handling of commit-ish values in maxSatisfying, minSatisfying

### ISSUE THREAD

**Issue by zbjornson** [npm/node-semver#201]
v5.4.0 seems to break handling of commit-ish values (e.g. `#master` and `#v2.1.0-a`), which affects at least yarn. I don't know if this is something yarn or semver should fix; I've opened an issue with yarn as well (https://github.com/yarnpkg/yarn/issues/4009).

v5.3.0:
```
> var semver = require("semver")
> semver.maxSatisfying([], "harmony-v2.8.22", true)
null
```

v5.4.0:
```
> var semver = require("semver")
> semver.maxSatisfying([], "harmony-v2.8.22", true)
TypeError: Invalid SemVer Range: harmony-v2.8.22
    at new Range (/root/temp2/node_modules/semver/semver.js:776:11)
    at Function.maxSatisfying (/root/temp2/node_modules/semver/semver.js:1156:18)
    at repl:1:8
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:73:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:340:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:538:10)
```

Bisected back to https://github.com/npm/node-semver/commit/32802c53503f67e5ebfd8c59aadf0fcec5d6a4a1.

**Comment by isaacs** [comment]
Well that's a bug.  One sec.

**Comment by isaacs** [comment]
32802c53503f67e5ebfd8c59aadf0fcec5d6a4a1 is the culprit.  Easy fix coming.

**Comment by zbjornson** [comment]
Thanks for the prompt fix!
