### ISSUE TITLE
Cannot install `semver`

### ISSUE THREAD

**Issue by robertherdzik** [npm/node-semver#205]
Hi, I have problem with installing `semver` using `npm install --save semver` commend. 
I get following terminal error:

```
npm install --save semver                                                                            0 < 19:20:11
module.js:491
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
```

Could you guys help me with my problem?

**Comment by isaacs** [comment]
That error is coming out of npm itself.  Can you install anything?  Is your npm installation messed up?

**Comment by robertherdzik** [comment]
You have right I had `npm` messed up. Reinstall, fixed my issue. Thanks :)
