### ISSUE TITLE
throw new TypeError('I

### ISSUE THREAD

**Issue by nicholasess** [npm/node-semver#267]
Hi everyone!
yesterday started this error in two projects, which solution is feasible?

```
/node_modules/semver/semver.js:296
    throw new TypeError('I
                        ^^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:84:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:312:10)
    at Module._compile (internal/modules/cjs/loader.js:684:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

**Comment by nicholasess** [comment]
@isaacs @pjohnmeyer please, publish code to npm package.

Code from npm install semver
![image](https://user-images.githubusercontent.com/3238901/52226627-a29d4f00-2894-11e9-9187-5efd96660e6b.png)

Code from repository
https://github.com/npm/node-semver/blob/master/semver.js#L296

This is breaking many libs that use semver as dependencies

**Comment by pjohnmeyer** [comment]
@nicholasess I am not a maintainer and cannot publish this package.

**Comment by pjohnmeyer** [comment]
@nicholasess I do not know but I've had good luck contacting npm support for pressing issues: https://www.npmjs.com/support

**Comment by nicholasess** [comment]
@pjohnmeyer I created um tweet and I will send to support

thanks man

**Comment by pjohnmeyer** [comment]
@nicholasess You may have a corrupt download; try blowing away your node cache and re-installing. I only say this because this package hasn't had a new version published for 4 months according to https://www.npmjs.com/package/semver

**Comment by nicholasess** [comment]
@pjohnmeyer I will try, but happened of a hour to other, this was working

**Comment by pjohnmeyer** [comment]
I just updated `npm` from 6.4.1 to 6.7.0, which updated semver from 5.5.0 to 5.6.0. I do not see this issue.

**Comment by isaacs** [comment]
Yeah, this is definitely a package manager issue, not a semver module issue.  Please report the issue to yarn, if that's the one you're using.

**Comment by joshxyzhimself** [comment]
can confirm `yarn cache clean` worked
