### ISSUE TITLE
[BUG] TypeError: Invalid Version: ~5.6.1

### ISSUE THREAD

**Issue by iKrishnaSahu** [npm/node-semver#419]
# What / Why
A tilde(~) version in lt breaks with invalid version error

### Current Behavior

`TypeError: Invalid Version: ~5.6.1
    at new SemVer (C:\Projects\projects\npm\ruf-monorepo\node_modules\semver\classes\semver.js:38:13)
    at compare (C:\Projects\projects\npm\ruf-monorepo\node_modules\semver\functions\compare.js:3:32)
    at Object.lt (C:\Projects\projects\npm\ruf-monorepo\node_modules\semver\functions\lt.js:2:29)`

### Steps to Reproduce

`semver.lt('5.6.0', '~5.6.1')`

### Expected Behavior

This should return true/false.

Is ~ tilde version not supported in lt/lte?

## Version

"semver": "^7.3.5",

**Comment by ljharb** [comment]
lt/lte take versions. A tilde denotes a range. There’s not really any “less than” that makes sense with a range.

**Comment by iKrishnaSahu** [comment]
@ljharb Okay. Thanks for the clarification.
