### ISSUE TITLE
NPM FETCH_ERROR invalid json response body

### ISSUE THREAD

**Issue by Nit-nit** [npm/node-semver#490]
```js
~ $ npm install colors
npm ERR! code FETCH_ERROR
npm ERR! errno FETCH_ERROR
npm ERR! invalid json response body at https://registry.npmjs.org/colors reason: Invalid response body while trying to fetch https://registry.npmjs.org/colors: EACCES: permission denied, link '/data/data/com.termux/files/home/.npm/_cacache/tmp/2333a390' -> '/data/data/com.termux/files/home/.npm/_cacache/content-v2/sha512/bc/dd/49bd25303bc6525c20b4725d57e056d8ae087fb0970b92d0709978ec3ad500a4dd349678495d5eba5761ebafeafabc2b023f8ec50a335e25f445c7b2b5e5'
```

log file
```js
0 verbose cli /data/data/com.termux/files/usr/bin/node /data/data/com.termux/files/usr/bin/npm
1 info using npm@8.19.2
2 info using node@v18.7.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 7ms
5 timing config:load:file:/data/data/com.termux/files/usr/lib/node_modules/npm/npmrc Completed in 41ms
6 timing config:load:builtin Completed in 41ms
7 timing config:load:cli Completed in 7ms
8 timing config:load:env Completed in 2ms
9 timing config:load:project Completed in 11ms
10 timing config:load:file:/data/data/com.termux/files/home/.npmrc Completed in 4ms
11 timing config:load:user Completed in 4ms
12 timing config:load:file:/data/data/com.termux/files/usr/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 1ms
14 timing config:load:validate Completed in 2ms
15 timing config:load:credentials Completed in 6ms
16 timing config:load:setEnvs Completed in 4ms
17 timing config:load Completed in 89ms
18 timing npm:load:configload Completed in 89ms
19 timing npm:load:mkdirpcache Completed in 5ms
20 timing npm:load:mkdirplogs Completed in 3ms
21 verbose title npm install colors
22 verbose argv "install" "colors"
23 timing npm:load:setTitle Completed in 4ms
24 timing config:load:flatten Completed in 12ms
25 timing npm:load:display Completed in 19ms
26 verbose logfile logs-max:10 dir:/data/data/com.termux/files/home/.npm/_logs
27 verbose logfile /data/data/com.termux/files/home/.npm/_logs/2022-10-09T10_05_29_632Z-debug-0.log
28 timing npm:load:logFile Completed in 24ms
29 timing npm:load:timers Completed in 1ms
30 timing npm:load:configScope Completed in 0ms
31 timing npm:load Completed in 151ms
32 timing arborist:ctor Completed in 3ms
33 silly logfile done cleaning log files
34 timing idealTree:init Completed in 170ms
35 timing idealTree:userRequests Completed in 6ms
36 silly idealTree buildDeps
37 silly fetch manifest colors@*
38 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
39 http fetch GET 200 https://registry.npmjs.org/colors 1074ms (cache miss)
40 silly placeDep ROOT colors@ REPLACE for:  want: *
41 timing idealTree:#root Completed in 1110ms
42 timing idealTree:node_modules/colors Completed in 0ms
43 timing idealTree:buildDeps Completed in 1115ms
44 timing idealTree:fixDepFlags Completed in 7ms
45 timing idealTree Completed in 1304ms
46 timing command:install Completed in 1350ms
47 verbose type invalid-json
48 verbose stack FetchError: invalid json response body at https://registry.npmjs.org/colors reason: Invalid response body while trying to fetch https://registry.npmjs.org/colors: EACCES: permission denied, link '/data/data/com.termux/files/home/.npm/_cacache/tmp/2333a390' -> '/data/data/com.termux/files/home/.npm/_cacache/content-v2/sha512/bc/dd/49bd25303bc6525c20b4725d57e056d8ae087fb0970b92d0709978ec3ad500a4dd349678495d5eba5761ebafeafabc2b023f8ec50a335e25f445c7b2b5e5'
48 verbose stack     at Response.json (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/minipass-fetch/lib/body.js:79:13)
48 verbose stack     at async RegistryFetcher.packument (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:99:25)
48 verbose stack     at async RegistryFetcher.manifest (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:124:23)
48 verbose stack     at async [nodeFromEdge] (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1061:19)
48 verbose stack     at async [buildDepStep] (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:930:11)
48 verbose stack     at async Arborist.buildIdealTree (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:211:7)
48 verbose stack     at async Promise.all (index 1)
48 verbose stack     at async Arborist.reify (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:153:5)
48 verbose stack     at async Install.exec (/data/data/com.termux/files/usr/lib/node_modules/npm/lib/commands/install.js:145:5)
48 verbose stack     at async module.exports (/data/data/com.termux/files/usr/lib/node_modules/npm/lib/cli.js:78:5)
49 verbose cwd /data/data/com.termux/files/home
50 verbose Linux 4.9.186-perf-g131f907
51 verbose node v18.7.0
52 verbose npm  v8.19.2
53 error code FETCH_ERROR
54 error errno FETCH_ERROR
55 error invalid json response body at https://registry.npmjs.org/colors reason: Invalid response body while trying to fetch https://registry.npmjs.org/colors: EACCES: permission denied, link '/data/data/com.termux/files/home/.npm/_cacache/tmp/2333a390' -> '/data/data/com.termux/files/home/.npm/_cacache/content-v2/sha512/bc/dd/49bd25303bc6525c20b4725d57e056d8ae087fb0970b92d0709978ec3ad500a4dd349678495d5eba5761ebafeafabc2b023f8ec50a335e25f445c7b2b5e5'
56 verbose exit 1
57 timing npm Completed in 2051ms
58 verbose unfinished npm timer reify 1665309930317
59 verbose unfinished npm timer reify:loadTrees 1665309930350
60 verbose code 1
61 error A complete log of this run can be found in:
61 error     /data/data/com.termux/files/home/.npm/_logs/2022-10-09T10_05_29_632Z-debug-0.log
```

**Comment by lukekarrys** [comment]
This doesn't look to be an issue with the `semver` package. If you're having troubling installing packages, you can open an issue on the `npm/cli` repo: https://github.com/npm/cli/issues/new/choose
